
const SET_AMOUNT='SET_AMOUNT'
const SET_CRYPTO='SET_CRYPTO'
const SET_COUNTRY='SET_COUNTRY'
const SET_USER='SET_USER'
const SET_CURRENCIES='SET_CURRENCIES'

export { SET_AMOUNT, SET_CRYPTO, SET_COUNTRY, SET_USER, SET_CURRENCIES }